# Generated by Django 5.0.6 on 2024-05-11 23:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
